### ISSUE TITLE
Deprecation warning: include

### ISSUE THREAD

**Issue by jswetzen** [Oefenweb/ansible-ssh-keys#11]
I get a warning from the use if 'include' which can apparently be replaced by 'import_tasks' or 'include_tasks'.

> [DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions. This feature will be removed in a future
release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is discouraged. The module documentation details page may explain more about this rationale.. This feature will be removed in
 a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

**Comment by tersmitten** [comment]
Fixed in https://github.com/Oefenweb/ansible-ssh-keys/releases/tag/v2.1.1
