### ISSUE TITLE
Private key generation

### ISSUE THREAD

**Issue by ghost** [Oefenweb/ansible-ssh-keys#14]
Any way this can generate a key pair instead of putting private keys in the playbook?

**Comment by tersmitten** [comment]
Not really, but you can have a `pre_task` do it for you (locally)

**Comment by ghost** [comment]
That's a good idea! I'll give it a go.

**Comment by nkakouros** [comment]
@tersmitten Is this a design decision? Would you accept a PR?

**Comment by tersmitten** [comment]
Please describe what you want to implement @tterranigma

**Comment by nkakouros** [comment]
I was thinking of an option to generate private-public key pairs and moving those around, placing them in authorized_keys, etc.

**Comment by nkakouros** [comment]
@tersmitten So would there be interest in that?

**Comment by tersmitten** [comment]
Yes, but please try to isolate this new feature as far as possible so it doesn't change existing features

**Comment by tersmitten** [comment]
Fixed in #16
