### ISSUE TITLE
Role fails when no authorized_keys specified

### ISSUE THREAD

**Issue by mvdriel** [Oefenweb/ansible-ssh-keys#4]
Role fails when no authorized_keys specified for a user. Error: `could not find 'authorized_keys' key in iterated item`

**Comment by tersmitten** [comment]
@mvdriel You've build it yourself :-)

Maybe do something like this `- "{{ authorized_keys | default([]) }}`? Can you test it?

This is probably also an issue for public and private keys

**Comment by mvdriel** [comment]
@tersmitten Yes and no, when there was only one keys array (authorized_keys) per user, it would be strange to not specify this one.

I already tried your suggestion, but it doesn't seem to be so easy. There is discussion about a related feature request, see https://github.com/ansible/ansible/issues/9827

@tersmitten What do you think about my "ugly" patch?

**Comment by tersmitten** [comment]
It is a solution, but so much more code :-( Wouldn't it be easier to change the documentation and make the properties required. At least `[]`?
