### ISSUE TITLE
Group option for private keys

### ISSUE THREAD

**Issue by mvdriel** [Oefenweb/ansible-ssh-keys#8]
I would like to make a private key accessible for a group, but although this option seems to be available in the configuration, it doesn't work caused by the applied permission 600 on private keys. How about read permission for the group when there is a group specified?

In the previous version it was possible to workaround this by doing something like this:

> owner: www-data
> home: /etc/cacti

**Comment by tersmitten** [comment]
Make mode configurable? With the current mode as default.

**Comment by mvdriel** [comment]
@tersmitten Good idea! I will implement this today or tomorrow.

**Comment by tersmitten** [comment]
Thanks

**Comment by tersmitten** [comment]
Fixed in #9
